export {
  COST_PREFERENCES,
  DEFAULT_REQUIREMENTS,
  LATENCY_PREFERENCES,
  RELIABILITY_LEVELS,
  WORKLOAD_CLASSES,
  isWorkloadClass,
  validateWorkload,
  type CostPreference,
  type LatencyPreference,
  type ReliabilityLevel,
  type WorkloadClass,
  type WorkloadDefinition,
  type WorkloadRequirements,
} from "./workload.js";
